[package]
name = "integration-tests"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
readme = "README.md"
publish = false
resolver = "2"

[dev-dependencies]
anyhow = { workspace = true }
borsh = { workspace = true, features = ["rc"] }
tempfile = { workspace = true }

sov-modules-api = { git = "https://github.com/Sovereign-Labs/sovereign-sdk", branch = "nightly" }
sov-state = { git = "https://github.com/Sovereign-Labs/sovereign-sdk", branch = "nightly" }
sov-rollup-interface = { git = "https://github.com/Sovereign-Labs/sovereign-sdk", branch = "nightly" }
sov-schema-db = { path = "../../../full-node/db/sov-schema-db" }
sov-data-generators = { path = "../../utils/sov-data-generators" }
sov-modules-stf-template = { path = "../../sov-modules-stf-template" }
sov-modules-macros = { path = "../../sov-modules-macros" }

sov-chain-state = { path = "../sov-chain-state" }
sov-value-setter = { path = "../examples/sov-value-setter" }
