[package]
name = "sov-module-schemas"
description = "A dummy crate that stores as files the JSON Schemas for all Sovereign modules"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
readme = "README.md"
resolver = "2"

[build-dependencies]
sov-modules-api = { path = "../sov-modules-api" }
sov-rollup-interface = { git = "https://github.com/Sovereign-Labs/sovereign-sdk", branch = "nightly", features = ["mocks"] }

# Modules
sov-accounts = { path = "../module-implementations/sov-accounts" }
sov-bank = { path = "../module-implementations/sov-bank" }
sov-prover-incentives = { path = "../module-implementations/sov-prover-incentives" }
sov-sequencer-registry = { path = "../module-implementations/sov-sequencer-registry" }
sov-evm = { path = "../module-implementations/sov-evm", features = ["experimental"] }
sov-election = { path = "../module-implementations/examples/sov-election" }
sov-value-setter = { path = "../module-implementations/examples/sov-value-setter" }
