[package]
name = "sov-data-generators"
description = "A set of generator utils used to automatically produce and serialize transaction data"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
readme = "README.md"
resolver = "2"


[dependencies]
sov-modules-api = { path = "../../sov-modules-api", default-features = false }
sov-modules-stf-template = { path = "../../sov-modules-stf-template" }
sov-value-setter = { path = "../../module-implementations/examples/sov-value-setter", default-features = false }
sov-election = { path = "../../module-implementations/examples/sov-election", default-features = false }
sov-bank = { path = "../../module-implementations/sov-bank", default-features = false }
sov-state = { path = "../../sov-state", default-features = false }
sov-rollup-interface = { git = "https://github.com/Sovereign-Labs/sovereign-sdk", branch = "nightly" , features = ["mocks"] }

borsh = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }

[features]
default = ["mocks", "native"]
mocks = []
native = [
    "sov-modules-api/native",
    "sov-state/native",
    "sov-bank/native",
    "sov-election/native",
    "sov-value-setter/native",
]