[package]
name = "sov-blob-storage"
description = "A Sovereign SDK module for holding blobs from Data Availability Layer"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
readme = "README.md"

resolver = "2"


[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true }
bincode = { workspace = true }
tracing = { workspace = true }
hex = { workspace = true }

sov-rollup-interface = {git = "https://github.com/Sovereign-Labs/sovereign-sdk", rev = "6371c32", version = "0.1" }
sov-modules-api = { git = "https://github.com/Sovereign-Labs/sovereign-sdk", rev = "6371c32", version = "0.1", default-features = false, features = ["macros"] }
sov-modules-macros = { path = "../../sov-modules-macros", version = "0.1" }
sov-state = { git = "https://github.com/Sovereign-Labs/sovereign-sdk", rev = "6371c32", version = "0.1", default-features = false }
sov-sequencer-registry = { git = "https://github.com/Sovereign-Labs/sovereign-sdk", rev = "6371c32", version = "0.1", default-features = false }


# TODO: these 5 can be deleted, after: https://github.com/Sovereign-Labs/sovereign-sdk/issues/524
serde = { workspace = true, optional = true }
schemars = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
jsonrpsee = { workspace = true, optional = true }
clap = { workspace = true, optional = true }

[dev-dependencies]
sov-modules-api = { git = "https://github.com/Sovereign-Labs/sovereign-sdk", rev = "6371c32", version = "0.1" }
sov-rollup-interface = { git = "https://github.com/Sovereign-Labs/sovereign-sdk", rev = "6371c32" , features = ["mocks"] }
sov-bank = { git = "https://github.com/Sovereign-Labs/sovereign-sdk", rev = "6371c32", version = "0.1" }
tempfile = { workspace = true }

[features]
default = ["native"]
native = [
    "sov-modules-api/native",
    "sov-state/native",
    "sov-modules-macros/native",
    "sov-sequencer-registry/native",
    "jsonrpsee",
    "schemars",
    "serde",
    "serde_json",
]
