[package]
name = "sov-modules-macros"
description = "Macros for use with the Sovereign SDK module system"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
readme = "README.md"
resolver = "2"
autotests = false

[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/all_tests.rs"

[dev-dependencies]
serde_json = "1"
tempfile = "3"
jsonrpsee = { workspace = true, features = ["macros", "http-client", "server"] }
trybuild = "1.0"

sov-modules-api = { git = "https://github.com/Sovereign-Labs/sovereign-sdk", branch = "nightly", version = "0.1", default-features = false }
sov-state = { git = "https://github.com/Sovereign-Labs/sovereign-sdk", branch = "nightly", version = "0.1", default-features = false }
sov-bank = { git = "https://github.com/Sovereign-Labs/sovereign-sdk", branch = "nightly", version = "0.1", features = ["native"] }
serde = { workspace = true }
clap = { workspace = true }

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true }
jsonrpsee = { workspace = true, features = ["http-client", "server"], optional = true }
proc-macro2 = "1.0"
quote = "1.0"
schemars = { workspace = true }
syn = { version = "1.0", features = ["full"] }

[features]
default = []
native = ["dep:jsonrpsee"]
